- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/request-for-enhancement.md
- .github/pull_request_template.md
- CODEOWNERS
- LICENSE
- README.md
> setup github repo

- data/distro-defs.yml
* Fixes: No such command: data[copr-repo]. Please use /usr/bin/dnf --help
[y/n] yes
> Fix build error

- .github/workflows/build.yml
Fixes issue # (delete if not relevant)
*
*
*
[y/n]
> add el8 and el9 matrix builds

- configure.ac
- ovirt-node-ng.spec.in
* Build oVirt Node 4.4.10.2 shipping several high severity CVE fixes
[y/n] yes
> oVirt Node 4.4.10.2 build

- .github/workflows/build.yml
* backporting github actions workflow to 4.4 branch
[y/n] y
> backport automation to 4.4 branch

- .github/workflows/build.yml
- build.sh
* add missing script
[y/n] yes
> Add 44 automation

- data/distro-defs.yml
* Prepare configuration for 4.5.0 alpha
[y/n] y
> Prepare for 4.5.0 alpha

- .github/workflows/build.yml
* build oVirt Node daily and report build issues automatically.
[y/n] yes
> automation: build daily and report issues

- data/distro-defs.yml
* enable testing repos for 4.5 alpha
[y/n] yes
> defs: prepare for 4.5 alpha

- scripts/derive-boot-iso.sh
* Backported deprecated isoinfo patches to ovirt-4.5 branch
[y]
> Backport isoinfo fixes to 4.5

- configure.ac
* build 4.5.0 for alpha
[y/n] y
> build: 4.5.0

- configure.ac
- data/distro-defs.yml
* switch to signed repos for 4.5.0 GA
[y/n] y
> build: ovirt-node-ng-image 4.5.0

- configure.ac
- ovirt-node-ng.spec.in
> Build 4.5.0.2

- .github/workflows/build.yml
* Use the new delete_before_upload function of the ovirt-resources-upload action
[y]
> Use delete_before_upload function of ovirt-resources-upload

- ovirt-node-ng.spec.in
* partially reverting 14f48fd lowering imgbased requirement as it broke upgrade from older versions.
y
> fix broken update on imgbased requirement

- build.sh
- data/distro-defs.yml
As for issues #46 and #49, preparing for building node based on alma/rocky.
Needs URLs to the respective repos and boot.iso.
We'll need to find compute power for buidling respective ISO and publish the result for testing it.
> Preparing for nightly master on rocky/alma

- build.sh
- data/distro-defs.yml
* updated references for AlmaLinux 9.0 GA
y
> Fix almalinux refs after 9.0 GA

- build.sh
- data/distro-defs.yml
* backport to 4.5 branch for PR #50
y
> Preparing for 4.5.1 on rocky/alma 9

- configure.ac
> build: 4.5.1_rc2

- configure.ac
- data/distro-defs.yml
- ovirt-node-ng.spec.in
> build: ovirt-node-ng-image 4.5.1

- configure.ac
- data/distro-defs.yml
* Post-build 4.5.1 (4.5.2-0.0)
[y/n]
> build: post ovirt-node-ng-image 4.5.1

- configure.ac
* Updated the next version to 4.5.1.1 (down-bumping it from the previous 4.5.2)
[y]
> Post-build 4.5.1 update (to 4.5.1.1)

- README.md
* Add more info about what oVirt Node is, where to get it and how to contribute.
y
> README: add more info

- configure.ac
> build: 4.5.2_rc1

- configure.ac
> Bump to 4.5.3

- configure.ac
- data/distro-defs.yml
- ovirt-node-ng.spec.in
> build: ovirt-node-ng-image 4.5.2

- scripts/create-product-img.sh
Added code to show the version and branch of the code.
* Added code to show the version and branch in the scripts/create-product-img.sh
[y]
> Added some debugging to scripts/create-product-img.sh

- build.sh
Fixes issue # (delete if not relevant)
* Display GITHUB_* variable values prior to build
[y]
> Show GITHUB_* variables

- scripts/create-product-img.sh
* Fixed scripts/create-product-img.sh version generation logic for the GitHub flow
[y]
> Fixed scripts/create-product-img.sh for GitHub flow

- configure.ac
- data/distro-defs.yml
> build: 4.5.3_rc1

- configure.ac
- ovirt-node-ng.spec.in
* Bump patch for 4.5.3.1 Async release
[y]
> build: 4.5.3.1 Async

- configure.ac
- ovirt-node-ng.spec.in
* Bump patch for 4.5.3.2 Async
[y]
> build: 4.5.3.2 Async

- configure.ac
- ovirt-node-ng.spec.in
> build: 4.5.4 GA

- configure.ac
- ovirt-node-ng.spec.in
* Now that 4.5.4 has been released, bump to 4.5.5 for master
y
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>
> Bump to 4.5.5

- configure.ac
- ovirt-node-ng.spec.in
> Bump to 4.5.6

- scripts/renderks.py
Explicitly use the SafeLoader
Fixes issue #21 
* be explicit in which loader to use (in this case SafeLoader)
*
*
Yes
> Fix warnings in renderks
